### ISSUE TITLE
QA mode

### ISSUE THREAD

**Issue by planemad** [Project-OSRM/osrm-frontend-v2#102]
Would be great to have a specialized mode for testing along with some extra debugging info. This is an issue with the previous frontend where we would have to constantly enable the small components layer, but this is not very relevant for the average user. 

**Immediate need**
- [x] Enable small components by default https://github.com/Project-OSRM/osrm-frontend-v2/issues/108
- [x] OSM mapnik layer as default (since more tags are rendered that helps in visual debugging) https://github.com/Project-OSRM/osrm-frontend-v2/issues/108

**Good to have**
- **[BACKEND]** Automatically nudge every point in order to find the failure waypoint and zoom to it. Currently we do this manually for every issue. https://github.com/Project-OSRM/osrm-frontend-v2/issues/109
- Ratio of route distance to line of sight distance. A ratio over 2 is an indication of a suboptimal route that we could inspect. https://github.com/Project-OSRM/osrm-frontend-v2/issues/117
- Ability to load barriers and access restrictions from overpass and overlay it https://github.com/Project-OSRM/osrm-frontend-v2/issues/110
- View unresolved notes in the area https://github.com/Project-OSRM/osrm-frontend-v2/issues/118

**Comment by amyleew** [comment]
> Enable small components by default
> OSM mapnik layer as default (since more tags are rendered that helps in visual debugging)
> Ratio of route distance to line of sight distance. A ratio over 2 is an indication of a suboptimal route that we could inspect.

@planemad ^^ should be easy fixes. To be clear... you're suggesting an alternative map for QA-ing?

**Comment by planemad** [comment]
@amyleew yes, Mapbox Streets is not very useful for this purpose since access restrictions and barriers are not rendered.

**Comment by TheMarex** [comment]
We could simply save this preferences in a cookie. That way you only need to configure language/layer/unit of measurement once.

**Comment by amyleew** [comment]
> View unresolved notes in the area

@planemad - Is this data available via mapID like `small components`?

**Comment by amyleew** [comment]
> Ratio of route distance to line of sight distance. A ratio over 2 is an indication of a suboptimal route that we could inspect.

@lbud will that be relevant for most users?

**Comment by planemad** [comment]
@amyleew don't think so, the only way i'm aware of is to use the [OSM notes API](http://wiki.openstreetmap.org/wiki/API_v0.6#Map_Notes_API)

**Comment by amyleew** [comment]
@planemad - How would you prioritize these enhancements in order of necessity to QA?

**Comment by planemad** [comment]
@amyleew updated

**Comment by amyleew** [comment]
Thanks @planemad! Updated with links.

**Comment by amyleew** [comment]
@planemad - I've updated this ticket ^^ I've got links to the issues create for these enhancements, but have closed them in interest of getting this demo launched. Perhaps you are someone else can pick them up post-launch!
