### ISSUE TITLE
Zoom to waypoint

### ISSUE THREAD

**Issue by planemad** [Project-OSRM/osrm-frontend-v2#103]
This was a very handy feature in the old frontend to fine tune the location of waypoints without scroll dancing.

**Comment by amyleew** [comment]
@planemad - The waypoint input is intimately tied to the [LRM](https://github.com/perliedman/leaflet-routing-machine) plugin we are using. This is is an upstream issue, probably better suited as a feature request for that project.

**Comment by planemad** [comment]
tracking on https://github.com/perliedman/leaflet-routing-machine/issues/156

**Comment by amyleew** [comment]
thanks @planemad. re-opened...

**Comment by planemad** [comment]
@amyleew flagging this as important. We would waste significant time if we had to manually zoom into each point without this feature.

**Comment by amyleew** [comment]
@planemad - I've started this on the [`zoom`](https://github.com/Project-OSRM/osrm-frontend-v2/tree/zoom) branch here. I won't be able to implement this feature, but please feel free to pick it up...
