### ISSUE TITLE
Shortlink generation

### ISSUE THREAD

**Issue by planemad** [Project-OSRM/osrm-frontend-v2#104]
Used to use the shortlink quite a bit to share a route to someone over email. Also handy to have a neat link to post for reference in tickets.

**Comment by amyleew** [comment]
@planemad - In addition to linkable url? Not as short, but @lxbarth requested it as a better alternative to shortlink...

![image](https://cloud.githubusercontent.com/assets/4587826/9668648/c14d547c-5250-11e5-8830-015ecd7333c5.png)

**Comment by lbud** [comment]
Yeah, I think the `osrm.at/___` links are great and people use them a lot
