### ISSUE TITLE
Add `localStorage` for QA preferences

### ISSUE THREAD

**Issue by amyleew** [Project-OSRM/osrm-frontend-v2#108]
Ref: https://github.com/Project-OSRM/osrm-frontend-v2/issues/102, add https://www.npmjs.com/package/local-storage to save QA (and other user) preferences: 
- [x] Which `baselayer` user selects
- [x] Is `small components` checked

/cc @tristen @planemad

**Comment by amyleew** [comment]
Can't figure out how to change `baseLayer` based on saved preferences on `window.load` [src/index.js#L19-L46](https://github.com/Project-OSRM/osrm-frontend-v2/blob/3f6896ba3533da7e36a9b4ca723477b8c72c874d/src/index.js#L19-L46)

@tristen @mourner Any tips?

**Comment by mourner** [comment]
@amyleew rather than change checkboxes, you have to set the right layer at a Leaflet map level, e.g. here: https://github.com/Project-OSRM/osrm-frontend-v2/blob/3f6896ba3533da7e36a9b4ca723477b8c72c874d/src/index.js#L62

**Comment by amyleew** [comment]
@mourner - Pushing [`layer` value (object)](https://github.com/Project-OSRM/osrm-frontend-v2/blob/localStorage/src/index.js#L61) in [`window.onLoad`](https://github.com/Project-OSRM/osrm-frontend-v2/blob/localStorage/src/index.js#L18-L43) function based on [baselayers](https://github.com/Project-OSRM/osrm-frontend-v2/blob/localStorage/src/leaflet_options.js#L45-L50) in layerGroup but page is not initalizing with a map layer. [Repo](https://github.com/Project-OSRM/osrm-frontend-v2/tree/localStorage)

![image](https://cloud.githubusercontent.com/assets/4587826/9744742/ada73368-563b-11e5-9719-e82f9934c127.png)

/cc @tristen

**Comment by amyleew** [comment]
Fixed and merged ^^ 

@planemad - [try it out](http://project-osrm.org/osrm-frontend-v2/) :+1:

**Comment by planemad** [comment]
@amyleew :+1:
