### ISSUE TITLE
Marker point nudge

### ISSUE THREAD

**Issue by amyleew** [Project-OSRM/osrm-frontend-v2#109]
Automatically nudge every point in order to find the failure waypoint and zoom to it. Currently we do this manually for every issue.

cc @planemad

**Comment by planemad** [comment]
Woohoo, this will be so awesome!

**Comment by TheMarex** [comment]
What does `nudge` mean here? Can you elaborate @planemad?

**Comment by planemad** [comment]
@TheMarex the first step when we inspect [a failure](http://osrm.at/fjg) is to move each waypoint around to figure out which end has this issue. If moving the waypoint results in a route, the failure is at that end.

![untitled](https://cloud.githubusercontent.com/assets/126868/9700749/7d85aaa4-542c-11e5-8f01-fd8e539ad078.gif)

Following this, we have to refresh the page and then zoom to the problem waypoint for further investigation. If this part can be automated and we go straight to the problem area, it speeds up the process considerably.

cc @amyleew

**Comment by TheMarex** [comment]
@planemad How do you imagine this would work code wise? I'm just not seeing how you want to automate this at the frontend level.

Certainly we could do a lot better job at automating the diagnosis of this kind of failure but I think the frontend is the wrong place for this kind of analysis.

**Comment by planemad** [comment]
@TheMarex make separate directions requests by shifting each waypoint by a certain distance, eg. `lat += 0.1 * Math.random()` till we get a successful route. Not perfect, but its an easy way to reduce a lot of manual steps in the UI that we are doing currently.

Agree that this should ideally be in the backend. What do you suggest for now?

**Comment by emiltin** [comment]
maybe do a table query with half the points scattered around A and the other half around B?

**Comment by amyleew** [comment]
@planemad - Can you open a backend issue for this?
