### ISSUE TITLE
Dynamic overlay?

### ISSUE THREAD

**Issue by amyleew** [Project-OSRM/osrm-frontend-v2#110]
> Ability to load barriers and access restrictions from overpass and overlay it

@planemad - Could be a `map ID` that the team can access on `github` and update as necessary. Make sense? Would that work? Can't think of another way to add this feature...

Ideas @lbud @lxbarth ?

**Comment by planemad** [comment]
@amyleew that should work well. I sometimes experiment with new styles that can help with QA like the [unconnected roads layer](https://api.mapbox.com/v4/planemad.c2f80b8f/page.html?access_token=pk.eyJ1IjoicGxhbmVtYWQiLCJhIjoiemdYSVVLRSJ9.g3lbg_eN0kztmsfIPxa9MQ#4/46.53/7.29) and [road classification layer](https://api.mapbox.com/v4/planemad.5504651b/page.html?access_token=pk.eyJ1IjoicGxhbmVtYWQiLCJhIjoiemdYSVVLRSJ9.g3lbg_eN0kztmsfIPxa9MQ#7/22.558/78.129). Any way to easily customize the overlay layers will be useful.

**Comment by amyleew** [comment]
@planemad - Send me the `map id` for a version of [unconnected roads layer](https://api.mapbox.com/v4/planemad.c2f80b8f/page.html?access_token=pk.eyJ1IjoicGxhbmVtYWQiLCJhIjoiemdYSVVLRSJ9.g3lbg_eN0kztmsfIPxa9MQ#4/46.53/7.29) and [road classification layer](https://api.mapbox.com/v4/planemad.5504651b/page.html?access_token=pk.eyJ1IjoicGxhbmVtYWQiLCJhIjoiemdYSVVLRSJ9.g3lbg_eN0kztmsfIPxa9MQ#7/22.558/78.129) with a `transparent` basemap and I'll add them below `small components`

![image](https://cloud.githubusercontent.com/assets/4587826/9744904/91ad603c-563c-11e5-980a-ae8966e29043.png)

**Comment by planemad** [comment]
@amyleew 
- Unconnected Roads `planemad.8d3c7f25`
- Road Hierarchy `planemad.c2f80b8f`

**Comment by amyleew** [comment]
This one shouldn't be too complicated. You should try and add this @planemad. If you have questions along the way, I'll help where I can!
