### ISSUE TITLE
Have to hit enter twice on second input to geocode it

### ISSUE THREAD

**Issue by lbud** [Project-OSRM/osrm-frontend-v2#116]
When I geocode the first field, tab to the second, hit enter to geocode an address, nothing happens until I've pressed enter twice.
@amyleew

**Comment by amyleew** [comment]
@lbud - This is an upstream issue that if fixed would go against Nominatim's prohibit of typeahead (see [discussion](https://github.com/Project-OSRM/osrm-frontend-v2/issues/82)). Solution was to add instructions as `placeholder` text.

**Comment by perliedman** [comment]
Worth noting that the Photon geocoder (also supported by LRM if you use the latest Leaflet Control Geocoder version), supports typeahead and is based on Nominatim's data.

Mapbox's geocoder is also supported by LRM/Leaflet Control Geocoder and has typeahead, but the data quality outside the US (or at least in Sweden!) appears to be of lower quality.

To summarize: using a service with typeahead would improve the UX. (But I'm still very open to suggestions for improvements when typeahead is not available.)
