### ISSUE TITLE
Distance is rounted to 100kms?

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-frontend-v2#127]
A user just reported this on the mailing list.

Have a look at this route http://map.project-osrm.org/?z=3&center=26.509905,66.445313&loc=48.690960,11.074219&loc=-25.005973,24.960937&hl=en&ly=&alt=&df=&srv=

"14000 km, 174 h" Is the conversion/rounding going wrong somewhere?

/cc @perliedman

**Comment by perliedman** [comment]
LRM rounds distances with a precision that depends on the size of the distance. The idea behind is to make the intinerary instructions readable and understandable: if you're going 2096 meters to the next turn, you probably want to read "continue 2km", but if you're going 96 meters, you want to read "100m".

As currently implemented, it uses the same method to present the total distance, but less coarsly rounded. Apparently, for very long distances the rounding is still pretty coarse.

Maybe it would be better to always show the total distance as rounded to closest meter/kilometer, and remove any fancy rounding logic?

**Comment by TheMarex** [comment]
@perliedman yeah I think the rounding might be a little bit too fancy. It is not really clear that it is a rounded value, and you would not expect it to be. I think this is more of an issue with voice directions, but the logic that would govern that is independent from the frontend I think.
