### ISSUE TITLE
Link to OSRM with map center and start marker?

### ISSUE THREAD

**Issue by yohanboniface** [Project-OSRM/osrm-frontend-v2#132]
Hi,

From uMap, there is a link that allow to start a route in OSRM from a map point, which used to then open OSRM website on a given center and the start marker already set.

Here is an example of URL computed by uMap that used to work: http://map.project-osrm.org/?loc=51.52740913661656,-0.08299827575683594&hl=de

Is there a way to reproduce that behaviour with new website?

Thanks :)

Ref: https://github.com/umap-project/umap/issues/219

**Comment by TheMarex** [comment]
For external linking please use `openstreetmap.org`. E.G:

```
http://www.openstreetmap.org/directions?engine=osrm_car&route=49.760,6.644#map=9/49.5769/7.4048
```

**Comment by yohanboniface** [comment]
Right, thanks, I'll do that :)
