### ISSUE TITLE
URL regression

### ISSUE THREAD

**Issue by lxbarth** [Project-OSRM/osrm-frontend-v2#148]
Legacy links like on http://roads.mapazonia.org/ don't work anymore. It appears that a center property in the URL query part is needed. In addition, moving the map after landing from a legacy link destroys the legacy links location proeprties.

**Comment by amyleew** [comment]
Looks like adding zoom values to these queries ( `z=[number]` ) will fix this. 

**Broken link**
[http://map.project-osrm.org/?loc=-2.5701525797,-57.8703463558&loc=-2.7418427523,-58.034545884&output=json&z=0&hl=pt](http://map.project-osrm.org/?loc=-2.5701525797,-57.8703463558&loc=-2.7418427523,-58.034545884&output=json&z=0&hl=pt)

**Working link with `z=4` pass into query**
[http://map.project-osrm.org/?z=4&loc=38.929827%2C-77.007039&loc=-2.747148%2C-66.772126&output=json&z=0&hl=pt](http://map.project-osrm.org/?z=4&loc=38.929827%2C-77.007039&loc=-2.747148%2C-66.772126&output=json&z=0&hl=pt)

@tristen - Is there a good way to redirect links coming to the site that will add the zoom value to the query string? That seems like the best option here.

**Comment by joto** [comment]
@daniel-j-h: not quite the same, but similar. I had a link looking like this: "http://map.project-osrm.org/?dest=COORDINATES&amp;destname=SOMEADDRESS" which doesn't work any more. It would show the area around the coordinates and did a search on the address and put it in the destination field. The user then only had to fill out the start location.

**Comment by amyleew** [comment]
Still working on this... hoping to: 
-  pull in start and end points from the [query url](https://github.com/Project-OSRM/osrm-frontend-v2/blob/gh-pages/src/links.js#L44-L52)
- [pass as waypoint values](https://github.com/Project-OSRM/osrm-frontend-v2/blob/gh-pages/src/index.js#L197)
- then force [update of center point](https://github.com/Project-OSRM/osrm-frontend-v2/blob/gh-pages/src/index.js#L197)

cc @tristen

**Comment by amyleew** [comment]
Tested this all on http://roads.mapazonia.org/ and they are working as expected. 

Please test [`url-fix` branch](https://github.com/Project-OSRM/osrm-frontend-v2/tree/url-fix) locally before we `merge` @lxbarth.

cc @tristen

**Comment by amyleew** [comment]
@lxbarth - Made [final code simplification](https://github.com/Project-OSRM/osrm-frontend-v2/commit/ba9d7ea3ca44086fe8965c94f027214f6ba7d2ae) and [loosened zoom](https://github.com/Project-OSRM/osrm-frontend-v2/commit/2ce9639d0199615b1d0ad9680b15368e1910557d). If no objections, I'll be merging soon.

cc @tristen @TheMarex

**Comment by vgeorge** [comment]
Thanks!
