### ISSUE TITLE
router.project-osrm.org/viaroute response with incorrect unicode chars

### ISSUE THREAD

**Issue by ghost** [Project-OSRM/osrm-frontend-v2#150]
Consequently we've got this error :
SyntaxError: JSON.parse: bad control character in string literal at line 1 column 200 of the JSON data

**Comment by danpat** [comment]
There is currently a bug in the string handling during preprocessing that is corrupting street name data. We are waiting for a new code deployment to complete which should hopefully fix the problem.

**Comment by ghost** [comment]
thank you. What do you think when this problem will be fixed ( day or two ) ?

**Comment by danpat** [comment]
Hopefully, yes, on the next cycle.  The bug should be fixed by https://github.com/Project-OSRM/osrm-backend/pull/1812

The demo server updates daily, so it will pick up the new code of the next cycle.

**Comment by ghost** [comment]
ok, thank you

**Comment by ghost** [comment]
any news? i see it's still not fixed

**Comment by ghost** [comment]
![2015-12-13_1816](https://cloud.githubusercontent.com/assets/14829960/11767036/c5215a8e-a1c5-11e5-8822-e846fc67e5af.png)

**Comment by ghost** [comment]
fixed

**Comment by danpat** [comment]
Yeah, sorry, it takes a while for a code change to get deployed.
