### ISSUE TITLE
Demo website gpx link doesn't include route

### ISSUE THREAD

**Issue by trigpoint** [Project-OSRM/osrm-frontend-v2#156]
Clicking the GPX button on http://map.project-osrm.org results in a file containing a GPX header, but empty of any points. 

I would expect to see the route that has been calculated.

File contents
<?xml version="1.0" encoding="UTF-8"?><gpx creator="OSRM Routing Engine" version="1.1" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 gpx.xsd"><metadata><copyright author="Project OSRM"><license>Data (c) OpenStreetMap contributors (ODbL)</license></copyright></metadata><rte>""</rte></gpx>

**Comment by TheMarex** [comment]
We removed GPX support from the `5.0` series that is currently running on the demo sever. We need to remove the button as well.

**Comment by amyleew** [comment]
Fixed https://github.com/Project-OSRM/osrm-frontend/pull/163
