### ISSUE TITLE
Map cannot be dragged, search resuls not zoomed into, "l.format is not a function"

### ISSUE THREAD

**Issue by roman-yepishev** [Project-OSRM/osrm-frontend-v2#167]
Started 2-3 days ago.

The map @ http://map.project-osrm.org/ cannot be dragged more than once, after that debug console shows "l.format is not a function".

The object address are resolved, but the map is not panned to the markers.

Reproducible on FF45.0, Chrome 49.0.2623.87.

**Comment by MoKob** [comment]
Can confirm the problems. In addition, zooming disconnects the geometry from the map.

<img width="757" alt="screen shot 2016-03-21 at 14 16 26" src="https://cloud.githubusercontent.com/assets/12932279/13919880/51b6d972-ef70-11e5-8bfc-4a12c727f78d.png">

:eyes: @amyleew can you take a look at whats going on? At the moment the Demo Server is essentially unusable.

**Comment by amyleew** [comment]
@TheMarex is taking a look at this issue!

**Comment by TheMarex** [comment]
Should be fixed now. Sorry for that, did a module update and thought it would "just work".
