### ISSUE TITLE
URL is getting longer and longer

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-frontend-v2#168]
On IRC user eddy_ reported:

> Hi. http://map.project-osrm.org/ seems to be broken. The URL gets longer and longer when navigating a map and eventually the tile servers return 400 or 494 because the referrer is too long. Is this a known issue?

/cc @TheMarex @amyleew

**Comment by malenki** [comment]
I had a look at the site and can confirm the the behaviour for
Chromium 49.0.2623.87 on Debian stretch/sid (64-bit) and
Firefox ESR 45.0.1

**Comment by TheMarex** [comment]
Fixed in 6594f1ffea2357717e8aee7a31dbcd7c4ac8e51c

**Comment by daniel-j-h** [comment]
Perfect, demo server is usable and awesome again! :+1:

**Comment by amyleew** [comment]
thanks @TheMarex :+1:
