### ISSUE TITLE
Multiple services not in GUI

### ISSUE THREAD

**Issue by benjamin-rty** [Project-OSRM/osrm-frontend-v2#175]
There is a possiblity to give more then 1 service in the leaflet_options.js, But in the GUI only the first service is used. (see linke 141 in index.js)
There is no way to select an other service.

Is it possible to add this in the GUI ?

Thanks

**Comment by TheMarex** [comment]
Yeah that should be possible to add. If you want to give it a spin, let me know if you have any questions. :+1:

**Comment by benjamin-rty** [comment]
Can you implement this ?

**Comment by benjamin-rty** [comment]
I am not a programmer in js, so I can't do it mself... sorry

**Comment by mvl22** [comment]
Is anyone able to give any pointers, architecturally, how this could be added to the code?

For instance, would this need to be implemented at the osrm-frontend level mainly, or would this require support in the underlying Leaflet Routing Machine library?

**Comment by morganherlocker** [comment]
Duplicate; closing in favor of: https://github.com/Project-OSRM/osrm-frontend/issues/160

**Comment by barqshasbite** [comment]
I think this should be reopened. Issue 160 is not talking about the same thing from what I can tell.
