### ISSUE TITLE
Add Mapillary links

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-frontend-v2#181]
Would be great to look at pictures of streets to understand the situation on the ground better.

/cc @daniel-j-h

**Comment by daniel-j-h** [comment]
To give a bit of insight into how (non-local) debugging usually looks like. It's a mix of looking at:
- demo server frontend for routing
- demo server's raw json response
- small components layer
- osm data layer
- mapillary traces

e.g. https://github.com/Project-OSRM/osrm-backend/issues/2725#issuecomment-236658010
