### ISSUE TITLE
support osrm-backend vector tiles

### ISSUE THREAD

**Issue by julienfr112** [Project-OSRM/osrm-frontend-v2#182]

**Comment by danpat** [comment]
@julienfr112 You can view the vector tiles by hitting:

http://map.project-osrm.org/debug/

**Comment by danpat** [comment]
The main page is still using a raster tile source with Leaflet JS.  We're also using Leaflet Routing Machine to do the UI, so either we'd need to add vector features to LRM, or swap to/create an engine that can work with a vector map.  Not a small lift.

**Comment by julienfr112** [comment]
great debug. One more question : what are the pink ways ?

**Comment by danpat** [comment]
Pink lines are "small components", areas of the road network that are isolated from the rest for some reason (invalid turn restrictions, barriers, disconnected, incorrect oneways, etc).
