### ISSUE TITLE
need to change osrm fronted port 9966 to 80

### ISSUE THREAD

**Issue by nikhilve99** [Project-OSRM/osrm-frontend-v2#199]
hi ,

can you please describe me, how can i can the port number on osrm-frontend.As i need to make my server live.
for temp. purpose i need to run my server on 80.

Regards
Nikhil

**Comment by danpat** [comment]
@nikhilve99 `osrm-frontend` is a regular web project.  To serve it on port 80, you need to set up a webserver of some type (Apache, nginx, etc), and place the files from this project in a directory.  

The `npm start` server that's included is just for development purposes.

**Comment by nikhilve99** [comment]
is there any doc to configure on apache2.

Regards
Nikhil

**Comment by danpat** [comment]
Not part of this project.  You might try a guide like:  https://www.digitalocean.com/community/tutorials/how-to-configure-the-apache-web-server-on-an-ubuntu-or-debian-vps
