### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by prp-e** [Project-OSRM/osrm-frontend-v2#203]
I found that this file is used for localizations : 
```
/i18n/en.js
/i18n/de.js
/i18n/fr.js
```
but, text such as "Head east on Foo square" in sidebar are not there. How can I localize them? 
Regards.

**Comment by daniel-j-h** [comment]
=> https://github.com/Project-OSRM/osrm-text-instructions

The reason for this is osrm-text-instructions should be re-usable in many clients and not only this frontend. Please check open tickets there (and closed / merged pull requests, we had some translation pull requests during the last couple of days).

I'm closing this ticket here :)
