### ISSUE TITLE
Switch to language names instead of flags

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-frontend-v2#214]
I agree with @joto in https://github.com/Project-OSRM/osrm-frontend/issues/212 that we should not use flags. Apart from the cultural/political arguments made, we have also been incredibly bad at adding new flags. With the rate at which we are adding new translations, we should make adding them to osrm-frontend easy as well.

According to http://www.flagsarenotlanguages.com/blog/best-practice-for-presenting-languages/ showing the language name in it's local language is the way to go.

**Comment by daniel-j-h** [comment]
At the moment all flags are broken

![flags](https://cloud.githubusercontent.com/assets/527241/24039000/f6d274de-0b03-11e7-956a-e96a8c14fee5.png)

can you fix until next week when people at fossgis will take a look at the demo server

**Comment by daniel-j-h** [comment]
@mstock I can see language names on the Swiss site http://routing.osm.ch.
Any chance to bring it upstream?

**Comment by mstock** [comment]
Actually, the credits for the text-based language chooser on http://routing.osm.ch go to @datendelphin, in [befc38e7](https://github.com/sosm/osrm-frontend/commit/befc38e7e8876939fd6bca17bd92dfb9c1b46b27) of the [SOSM-fork of the OSRM frontend](https://github.com/sosm/osrm-frontend). Nonetheless, I just created a pull request (#228) which implements a language chooser based on language names, but using a different approach than the one on the Swiss OSRM instance.

**Comment by mstock** [comment]
Now that #228 has been merged and the change was rolled out on the [OSRM demo site](http://map.project-osrm.org/), I guess this could be considered as done.

**Comment by daniel-j-h** [comment]
Yep, thank you!
