### ISSUE TITLE
Multiple routes

### ISSUE THREAD

**Issue by AnixPasBesoin** [Project-OSRM/osrm-frontend-v2#226]
I've been unable to determine how to draw multiple routes on the same map using the frontend's code.
What I want to achieve, is to route a first set of waypoints with one routing service and then route a second set of waypoints with another routing service.
I also want to keep both routing itineraries (concatenate the two).
What's the cleanest way to do that?

**Comment by danpat** [comment]
@AnixPasBesoin I don't think there's going to be an easy way.  `osrm-frontend` depends heavily on https://github.com/perliedman/leaflet-routing-machine for route querying/drawing.

You might need to hack changes into LRM, or write custom code to call LRM twice to put results on the map.

At this stage, you should probably fork the `osrm-frontend` project and make your own customizations.  The frontend project is really designed to work with a single OSRM instance, so your needs are somewhat unique.

**Comment by daniel-j-h** [comment]
Closing here as not actionable on our side. Maybe you can use the frontend's alternative mechanism to draw multiple routes, and then only change how alternative routes look like in the CSS.
