### ISSUE TITLE
Master broken - input fields gone, markers not showing up, etc.

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-frontend-v2#249]
Looks like master is broken. There are some internal errors in the console showing up, the text input fields are gone and adding markers does not work at all (see image below). @DenisCarriere you added the last commits - care to have a look here?

Last "working" commit seems to be 07b0b9e7dd467cb1142ce4ede2a9b5cd875deba6 - it's also showing a 

> Exception InvalidInt: "undefined" is not a valid integer.

in the console, but at least it's not completely broken ..

![map0](https://user-images.githubusercontent.com/527241/27635831-f38e82b2-5c08-11e7-8a0e-ad926067b765.png)

cc @MoKob

**Comment by DenisCarriere** [comment]
Thanks for the heads up, I'll look into this.

I'm also noticing this warning.

```
Exception InvalidInt: "undefined" is not a valid integer.
```

It's coming from `parseLink`.

```javascript
function parseLink(link) {
  var q = qs.parse(link),
    parsedValues = {},
    options = {},
    k;
  try {
    parsedValues.zoom = _parseInteger(q.z);
    parsedValues.center = q.center && _parseCoord(q.center);
    parsedValues.waypoints = q.loc && q.loc.filter(function(loc) { return loc != ""; }).map(_parseCoord).map(
      function(coord) {
        return L.Routing.waypoint(coord);
      }
    );
    parsedValues.language = q.hl;
    parsedValues.alternative = q.alt;
    parsedValues.units = q.df;
    parsedValues.layer = q.ly;
    parsedValues.service = q.srv;
  } catch (e) {
    console.log("Exception " + e.name + ": " + e.message);
  }
```

**Comment by DenisCarriere** [comment]
@daniel-j-h on my latest commits I don't see the input fields being gone?

![image](https://user-images.githubusercontent.com/550895/27636692-a5250dae-5bda-11e7-83ca-92b526b97d7e.png)

**Comment by daniel-j-h** [comment]
I can reproduce this with Firefox and Chrome under Linux on commit b1df85e and so could @MoKob yesterday on his macOS.

![map1](https://user-images.githubusercontent.com/527241/27637151-f70db48e-5c0e-11e7-966b-1d79660b3832.png)

Seems like it's coming from

https://github.com/Project-OSRM/osrm-frontend/blob/1dc9d80df95309b3863ec377e9753db05477b61b/src/index.js#L119

**Comment by DenisCarriere** [comment]
@daniel-j-h Try changing these lines of code https://github.com/Project-OSRM/osrm-frontend/pull/250 in your local repo and try it again.

**Comment by daniel-j-h** [comment]
@DenisCarriere yep your changes make the frontend no longer trigger the parsing error. The problem ticketed in this ticket still persists: [local is undefined here](https://github.com/Project-OSRM/osrm-frontend/blob/1dc9d80df95309b3863ec377e9753db05477b61b/src/index.js#L119) seems to be the case.

**Comment by freenerd** [comment]
@daniel-j-h can you still reproduce on master? I can't.

**Comment by daniel-j-h** [comment]
Can still reproduce in both Firefox as well as Chrome. Steps to reproduce:
- clone repo
- npm install (my npm version is 5.2, node version is 4.8)
- npm run start

Same problem when changing the backend in `src/leaflet_options.js` between install and start.

**Comment by samuelleach** [comment]
Just to say - I have the same problem which I also reproduce via https://github.com/Project-OSRM/osrm-frontend/issues/249#issuecomment-315366717

This is the first time I'm trying to install the front end locally. My node version is 4.2.6 and my npm version is 3.5.2 (Ubuntu 16.0.4).

Here's a screenshot of the console:

![open source routing machine demo - google chrome_004](https://user-images.githubusercontent.com/1760038/28752820-36bf4172-7520-11e7-8cac-73b82ef6c25a.png)

**Comment by DenisCarriere** [comment]
I still can't replicate any errors, I've tried it on the following:
- Ubuntu 16.04
  - Node 4/7
- MacOS Sierra
  - Node 4/6/7

@samuelleach Can you confirm your environment variables, maybe it has to do with that.

@samuelleach Does it work if you use NodeJS 6+?

```js
const ZOOM = process.env.ZOOM || 13
const LABEL = process.env.LABEL || 'Car (fastest)'
const CENTER = process.env.CENTER || '38.8995, -77.0269'
const BACKEND = process.env.BACKEND || 'https://router.project-osrm.org'
const LANGUAGE = process.env.LANGUAGE || 'en'
```

**Comment by samuelleach** [comment]
Sorry for my slow response. I just tested your fix in #254 / https://github.com/Project-OSRM/osrm-frontend/pull/254/commits/a69feacc36b6a70f25c94e4b5df534996d3392fc and it now works.

**Comment by DenisCarriere** [comment]
👍

**Comment by daniel-j-h** [comment]
Yep that fixed it 👍 Thank you for the deep dive here!
