### ISSUE TITLE
Is OSRM down?

### ISSUE THREAD

**Issue by shravan91** [Project-OSRM/osrm-frontend-v2#260]
It seems the routing service is not working. Does anyone have more information on what the issue is?

![screen shot 2017-09-27 at 09 52 48](https://user-images.githubusercontent.com/3190951/30901877-b778d360-a369-11e7-9c59-ccaf16560fb3.png)

**Comment by daniel-j-h** [comment]
- http://project-osrm.org/
- https://www.mapbox.com/get-directions/
- https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server

**Comment by shravan91** [comment]
Thanks @daniel-j-h
