### ISSUE TITLE
new install osrm-frontend npm build error

### ISSUE THREAD

**Issue by anick012** [Project-OSRM/osrm-frontend-v2#264]
The error is appeared when tried to start local server:

nick@router:/opt/osrm-frontend$ npm start
> osrm-frontend@0.4.0 start /opt/osrm-frontend
> npm run build && npm run start-index

> osrm-frontend@0.4.0 build /opt/osrm-frontend
> npm run replace && npm run compile && cp node_modules/leaflet/dist/leaflet.css css/leaflet.css

> osrm-frontend@0.4.0 replace /opt/osrm-frontend
> node ./scripts/replace.js

/opt/osrm-frontend/scripts/replace.js:12
  let options = fs.readFileSync(filepath, 'utf8')
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by daniel-j-h** [comment]
You're probably on node v4.

I fixed this in https://github.com/Project-OSRM/osrm-frontend/commit/1dc9d80df95309b3863ec377e9753db05477b61b#diff-5c005e23953f09d4a3dcc5bfc3b7113f

but seems like it got re-introduced in https://github.com/Project-OSRM/osrm-frontend/commit/ef453d934a38076579d31c94642b022b15995d49#diff-5c005e23953f09d4a3dcc5bfc3b7113f

You need the `'use strict';` at the top. Can you change that and open a pull request for it?
