### ISSUE TITLE
configuring

### ISSUE THREAD

**Issue by engragy** [Project-OSRM/osrm-frontend-v2#268]
i have been trying to install osrm-backend and did it successfully and now i did install the awesome osrm-frontend and every thing is working
but i just want to configure the front end to use my local host  osrm-backend and my local tile server
i also want to set a default lat,lon,zoom and default map layer
can  you please help me with this

sorry if this is the wrong place to post this  ...

**Comment by daniel-j-h** [comment]
See https://github.com/Project-OSRM/osrm-frontend#changing-backends to point the frontend to your backend. Also in case you're using the Docker image see: https://github.com/Project-OSRM/osrm-frontend/blob/4c037ccfef2e3f9238d3f7ee60c9b3c8342032f0/docker/Dockerfile#L3-L8

**Comment by engragy** [comment]
thank you @daniel-j-h  for your reply , i have adjusted the "leaflet_options.js" file as described in #changing backeds to point to my local backend and also to point to my tile server and default zoom ,centre as i didn't build the backend using docker and it is now working fine at localhost:9966

but i have enabled proxy,proxy_http to direct port 9966 to localhost/osrm-front and then something strange happened , that it didn’t apply the edits i did in the "leaflet_options.js" file if i browse the frontend using localhost/osrm-front while the edits are applied if i browse through localhost:9966

what do you think this problem might be.

**Comment by daniel-j-h** [comment]
I don't know what your proxy / proxy_http thingy is. Sorry you need to debug this on your side.

**Comment by morganherlocker** [comment]
Thanks @daniel-j-h, this answers the question as it relates to OSRM.
