### ISSUE TITLE
Debug map is down

### ISSUE THREAD

**Issue by jcoupey** [Project-OSRM/osrm-frontend-v2#287]
I came across this during a discussion on the osrm IRC channel. Posting here as this seem to be the most relevant repo.

Currently when looking at http://map.project-osrm.org/debug/, no overlay is showing because the tiles can't be loaded. The requests generated by the frontend - such as http://router.project-osrm.org/tile/v1/car/tile(10479,25326,16).mvt - all report a `403` error.

When accessing using https at https://map.project-osrm.org/debug/, the loading is blocked all-together for me using Firefox because of a mixed-content issue. Console logs look like `Blocked loading mixed active content “http://router.project-osrm.org/tile/v1/car/tile(10478,25325,16).mvt”`.

**Comment by donnut** [comment]
I experience the same issue. On our local installation it works fine as all the routes are pointing to the same domain. It's a server configuration issue and I would love to have it solved because the debug option is really useful.

**Comment by jcoupey** [comment]
This is working properly for a long time now.
