### ISSUE TITLE
Pass and style print values

### ISSUE THREAD

**Issue by amyleew** [Project-OSRM/osrm-frontend-v2#52]
Print button currently is not properly passing map values to print.html page. It is passing entire query, i.e.,  [`http://amyleew.github.io/osrm-frontend/printing.html#z=13&center=38.899049%2C-77.026949&loc=38.902389%2C-77.032700&loc=38.891834%2C-77.146854&hl=en&ly=&alt=&df=metric&srv=`](http://amyleew.github.io/osrm-frontend/printing.html#z=13&center=38.899049%2C-77.026949&loc=38.902389%2C-77.032700&loc=38.891834%2C-77.146854&hl=en&ly=&alt=&df=metric&srv=)

But that is not populating the map on the page.

Once map values are passed, styling control for the route line and instructions will need to match that of the previous page. 

![image](https://cloud.githubusercontent.com/assets/4587826/9125996/06c7c60a-3c75-11e5-9fa2-b3464e280aa8.png)

/cc @lbud

**Comment by tristen** [comment]
Hey @amyleew see https://github.com/amyleew/osrm-frontend/commit/dec59123dd725ff538c8a0050bac8be21254c2bd

**Comment by amyleew** [comment]
fixed thanks @tristen... still needs styling so i'll leave open

**Comment by amyleew** [comment]
Styling here https://github.com/Project-OSRM/osrm-frontend-v2/issues/62
