### ISSUE TITLE
Add styling for alternative route 

### ISSUE THREAD

**Issue by amyleew** [Project-OSRM/osrm-frontend-v2#55]
Alt route is defined in route instructions but not clear on how to style an alt route line on the map in addition to main line styling.

![alt-route](https://cloud.githubusercontent.com/assets/4587826/9042224/4bb3d408-39db-11e5-861d-702c12b1d6ab.png)

**Comment by lbud** [comment]
@amyleew tricky as these get all hidden in LRM — [here](https://github.com/Project-OSRM/osrm-frontend-v2/commit/4b14f8b0a725081460ba2d408bca2f409ca4fe4c#diff-168726dbe96b3ce427e7fedce31bb0bcR89) it listens to the control's `routesfound` event (found in the [API documentation](http://www.liedman.net/leaflet-routing-machine/api/#l-routing-control)) which contains an array of 1 or 2 routes and adds the second to the map. (I didn't touch the line options or play with display/interaction of the line, all you!)

**Comment by lbud** [comment]
Ah, also just realized it doesn't remove the alternate route when the next event is fired. It's unfortunate that the show-all option isn't surfaced upstream (could PR if that would make sense?) so we'll have to remove the alt route, probably on the next `routingstart` event…

**Comment by amyleew** [comment]
Thanks @lbud! Line styling is looking good, now matching route with instructions. Closing here.

![image](https://cloud.githubusercontent.com/assets/4587826/9093364/bf74e306-3b79-11e5-8779-a1b3afcf98d7.png)
