### ISSUE TITLE
Main / alt routing click to select 

### ISSUE THREAD

**Issue by amyleew** [Project-OSRM/osrm-frontend-v2#61]
Per chat w/ @lbud - For routes with *alternative routes*, let's add functionality to allow the user to select either `main` or `alt` route and then jump user to that section of the instructions. 

![image](https://cloud.githubusercontent.com/assets/4587826/9126130/695b2e22-3c77-11e5-99a3-95085d7e103a.png)

**Comment by lbud** [comment]
@amyleew as a preview of what the functionality I'm working on in the lrm fork I have: clicking the alternate route will basically select that _as_ the main route 
![lrm-toggle](https://cloud.githubusercontent.com/assets/3170312/9126178/08a5c514-3c5f-11e5-8332-f265d7440f87.gif)

and will fire an event that indicates the newly selected route.

**Comment by amyleew** [comment]
@lbud :+1: :boom:

**Comment by amyleew** [comment]
Selection functionality w/ @lbud's [LRM altLines](https://github.com/lbud/leaflet-routing-machine/tree/altLines) branch.

Controlling display of routing instructions with https://github.com/Project-OSRM/osrm-frontend-v2/commit/a756e01d4ab708dbc1ebd55f65b208ac82490e82
