### ISSUE TITLE
Pass selected route for printing

### ISSUE THREAD

**Issue by amyleew** [Project-OSRM/osrm-frontend-v2#62]
Print button is only passing coors for the **main route** even if alternative route is selected by user.

![image](https://cloud.githubusercontent.com/assets/4587826/9318263/17fba470-4510-11e5-8f83-2bd5e4b87230.png)

![image](https://cloud.githubusercontent.com/assets/4587826/9318280/58ed065e-4510-11e5-8c16-a8687f35babb.png)

**Comment by lbud** [comment]
Hmm it looks to me like it is only going to the alternate route — but yeah, this is a bug. It's coming from [here](https://github.com/Project-OSRM/osrm-frontend-v2/blob/redesign/printing.js#L39), which currently hardcodes whatever line comes from the _last route_ in the array of possible routes (`alts[alts.length - 1]`). I'm working on a fix that makes the index of the selected alternative configurable, though it's also a little bit of upstream work :)

**Comment by amyleew** [comment]
Per chat with @lxbarth, let's hit this issue post-launch.
