### ISSUE TITLE
Fix icons in Firefox

### ISSUE THREAD

**Issue by amyleew** [Project-OSRM/osrm-frontend-v2#66]
![image](https://cloud.githubusercontent.com/assets/4587826/9333931/1bce40c8-459a-11e5-9052-69ca65594aea.png)

**Comment by amyleew** [comment]
Fixed https://github.com/Project-OSRM/osrm-frontend-v2/commit/aa2af5001c6a294affd87e10eb1252effdf75776 

Can you take a peek on your end @daniel-j-h ?

**Comment by daniel-j-h** [comment]
Icons look great now! One minor nitpick, while (re-)loading the page:
the icons are hidden by the browser's URL requests thingy at the bottom left.

![icons-loading](https://cloud.githubusercontent.com/assets/527241/9372389/4189de5e-46de-11e5-9429-f3b801e9ce79.jpg)

**Comment by amyleew** [comment]
@daniel-j-h I'll push that toolbar up a bit! Thanks

**Comment by amyleew** [comment]
Pushed it up a bit @daniel-j-h 
![image](https://cloud.githubusercontent.com/assets/4587826/9388471/ab6b14aa-4733-11e5-910e-260c8cba29a2.png)

Fixed https://github.com/Project-OSRM/osrm-frontend-v2/commit/ab3117679e1fa0d08c9aef774ac33e31e665a152
