### ISSUE TITLE
Add  "small components" layer

### ISSUE THREAD

**Issue by amyleew** [Project-OSRM/osrm-frontend-v2#72]
<img width="152" alt="screen shot 2015-08-19 at 12 45 02" src="https://cloud.githubusercontent.com/assets/25713/9354371/26a10388-4670-11e5-8b26-6664505b847a.png"> 

/cc @freenerd

**Comment by amyleew** [comment]
Added https://github.com/Project-OSRM/osrm-frontend-v2/commit/1c556ee00d1b78387f3930836b6135e878ede496

![image](https://cloud.githubusercontent.com/assets/4587826/9363957/9c2ded44-4677-11e5-845b-c78e12c176c5.png)

/cc @freenerd

**Comment by emiltin** [comment]
as a side note, the small components layer is computed based on the car profile. in case you enable routing other modes like bike or walking, the layer should optimally reflect this.

**Comment by amyleew** [comment]
thanks @emiltin. current build is car profile only, but good to keep in mind future builds.

**Comment by freenerd** [comment]
Can you disable small components by default? Only a small subset of users will ever be interested in them.

**Comment by amyleew** [comment]
Removed https://github.com/Project-OSRM/osrm-frontend-v2/commit/23fd70e7135743cc653ce498eabb57a74a8dd61b
