### ISSUE TITLE
Change drag marker to refresh route on drag not click

### ISSUE THREAD

**Issue by amyleew** [Project-OSRM/osrm-frontend-v2#73]
Currently refresh of route happens `on.releasee` make it `on.drag`

/cc @danpat

**Comment by danpat** [comment]
Consider putting a small timer in `on.drag` to prevent rapid dragging flooding the server with requests.  Only update the route when the timer expires, and renew the timer whenever `on.drag` occurs.  Something like 75-100ms should be almost unnoticeable and would greatly reduce the number of requests during dragging.

**Comment by danpat** [comment]
Something like:
```
  var drag_timeout;
  on.drag(function() {
     clearTimeout(drag_timeout);
     drag_timeout = setTimeout(function() { updateRoute(); }, 100);
  });
```

**Comment by amyleew** [comment]
@danpat - LRM has an option for [`routeWhileDragging`](http://www.liedman.net/leaflet-routing-machine/api/#l-routing-control) and `routeDragInterval`, which I've set to [`true`](https://github.com/Project-OSRM/osrm-frontend-v2/blob/redesign/index.js#L71) and [`100`](https://github.com/Project-OSRM/osrm-frontend-v2/blob/redesign/index.js#L79) but I'm not sure it's overriding properly but it's showing up as `false` in my [js/osrm.bundle.js](https://github.com/Project-OSRM/osrm-frontend-v2/blob/redesign/js/osrm.bundle.js) ... see anything I'm missing here?

**Comment by amyleew** [comment]
@danpat - Fixed https://github.com/Project-OSRM/osrm-frontend-v2/commit/dc7608f91db0697e0a84cb94d703ceed5c89d87d! Needs to be set twice in [`control`](https://github.com/Project-OSRM/osrm-frontend-v2/blob/redesign/index.js#L91) and [`plan`](https://github.com/Project-OSRM/osrm-frontend-v2/blob/redesign/index.js#L70).
