### ISSUE TITLE
Instructions overflowing

### ISSUE THREAD

**Issue by lbud** [Project-OSRM/osrm-frontend-v2#74]
When the window is too small, the directions overflow to the left of the instructions panel:
![image](https://cloud.githubusercontent.com/assets/3170312/9372398/ebcb38d2-4692-11e5-8a17-09563d59bb81.png)

**Comment by amyleew** [comment]
@lbud - Fixed https://github.com/Project-OSRM/osrm-frontend-v2/commit/47ffbdb349e1075d0f8bdd9db8dadd73b0fa7016
