### ISSUE TITLE
Clicking a waypoint to remove it

### ISSUE THREAD

**Issue by lbud** [Project-OSRM/osrm-frontend-v2#75]
(as a feature request) This is a pretty common interaction. Otherwise it becomes impossible to remove a waypoint right now.

**Comment by amyleew** [comment]
Returned `x` for added points in `geocoder` https://github.com/Project-OSRM/osrm-frontend-v2/commit/0e1babf1c83e92d58dc15027414b997fb2674d3a. Originally removed when I took away the `addWaypoints` button. Didn't realize it removed `x` for all waypoints. Thanks for the catch @lbud!

![image](https://cloud.githubusercontent.com/assets/4587826/9391443/cb842e5a-4744-11e5-9d7b-aa9a6785ba2a.png)
