### ISSUE TITLE
Switch between alternate routes via summaries

### ISSUE THREAD

**Issue by lbud** [Project-OSRM/osrm-frontend-v2#76]
a la
![image](https://cloud.githubusercontent.com/assets/3170312/9372441/555134f0-4693-11e5-9a3f-8f62f421afb6.png)
(the "Fulton Street" link alternates to the other route)
![image](https://cloud.githubusercontent.com/assets/3170312/9372452/65fe9680-4693-11e5-9ce9-a7908f93f16a.png)
or even
![image](https://cloud.githubusercontent.com/assets/3170312/9372483/dfe7bf6c-4693-11e5-8bc7-6cf9df5eab91.png)

— having some kind of metadata / textual cues as to why there are multiple lines and what each means can help to choose.

**Comment by amyleew** [comment]
@lbud Should we eventually add this to the updated demo as well for a 2nd way to swap between main and alt routes? Possibly by adding the [IRouteSummary](http://www.liedman.net/leaflet-routing-machine/api/#iroutesummary) linked below the current route's itinerary.

![image](https://cloud.githubusercontent.com/assets/4587826/9385607/53a29f08-4725-11e5-867a-4ed61381e1b5.png)
