### ISSUE TITLE
Set geocoder input to tab complete

### ISSUE THREAD

**Issue by amyleew** [Project-OSRM/osrm-frontend-v2#82]
Works with `Enter` only now. Change code to look for `blur` event instead.

/cc @lbud

**Comment by lbud** [comment]
I'd move this to pre-launch as I just realized the following does not work:

* Type address in first geocoder
* Tab to next geocoder, type address
* Hit enter. **Nothing happens**
* Hit enter again just for fun: _only the end geocoder gets geocoded/pin drop_

This is a really common pattern that should work before this is live.

**Comment by amyleew** [comment]
@lbud Looks like an upstream issue.

Basic [LRM example](http://www.liedman.net/leaflet-routing-machine/) finds both `start` and `end` points then routes with `tab` `tab` `enter`.
![image](https://cloud.githubusercontent.com/assets/4587826/9447026/1bf44fde-4a63-11e5-91f2-8c4741bceb55.png)

Doesn't work out the box with [`click to add waypoints` interaction](http://www.liedman.net/leaflet-routing-machine/tutorials/interaction/).
![image](https://cloud.githubusercontent.com/assets/4587826/9447093/74c0e5dc-4a63-11e5-88d1-e59cc379b964.png)

Reading a bit more on this, maybe I need to pass another option here?

**Comment by tristen** [comment]
Hey @lbud I tried the steps you outlined in https://github.com/Project-OSRM/osrm-frontend-v2/issues/82#issuecomment-133560757 from the [LRM example](http://www.liedman.net/leaflet-routing-machine/) and I'm re-creating it there too. It looks like this bug should be reported to the LRM project and not necessarily a launch blocker to the redesign?

**Comment by amyleew** [comment]
@perliedman Is looking into this issue: https://github.com/perliedman/leaflet-routing-machine/issues/148

**Comment by perliedman** [comment]
I'm not entirely sure what the best interaction would be, so if you have suggestions, feel free to add them to https://github.com/perliedman/leaflet-routing-machine/issues/148

**Comment by amyleew** [comment]
Thanks @perliedman!

Fixed https://github.com/Project-OSRM/osrm-frontend-v2/commit/1d2e65405f4492afea78e33ebb0f3b44385d494b

![image](https://cloud.githubusercontent.com/assets/4587826/9618320/9d28b47a-50d3-11e5-9442-e826466a27f1.png)

/cc @lbud
