### ISSUE TITLE
Can't do a second route

### ISSUE THREAD

**Issue by lbud** [Project-OSRM/osrm-frontend-v2#84]
The following does not work:

* Click two points to get a route
* `x` both geocoders to clear route
* Click twice more again to get a new route: these clicks do not add markers or change anything

@amyleew

**Comment by amyleew** [comment]
@lbud - Yes! New bug after implementing refresh fix: https://github.com/Project-OSRM/osrm-frontend-v2/issues/83

**Comment by amyleew** [comment]
Fixed https://github.com/Project-OSRM/osrm-frontend-v2/commit/74f94685d20c43caa750084d5b5d6320dca53c99
