### ISSUE TITLE
Swap # with ?

### ISSUE THREAD

**Issue by amyleew** [Project-OSRM/osrm-frontend-v2#88]
In `url`.

**Comment by amyleew** [comment]
Throwing error 
```
Uncaught TypeError: Cannot read property 'lat' of undefined`. 
11.L.Projection.SphericalMercator.project @ leaflet-src.js:1420
11.L.CRS.latLngToPoint @ leaflet-src.js:1460
11.L.Map.L.Class.extend.project @ leaflet-src.js:1955
11.L.Map.L.Class.extend._getNewTopLeftPoint @ leaflet-src.js:2278
11.L.Map.L.Class.extend._resetView @ leaflet-src.js:2094
11.L.Map.include.setView @ leaflet-src.js:873225../src/leaflet_options @ printing.js:22
```
Errors here [/printing.js#22](https://github.com/Project-OSRM/osrm-frontend-v2/blob/redesign/printing.js#L22) But threw some on [this function](https://github.com/Project-OSRM/osrm-frontend-v2/blob/redesign/printing.js#L65-L70) while testing, that syntax look legit @danpat ?

**Comment by danpat** [comment]
it looks like `parsedOptions.center` is not a valid object.  It's still being set from `window.location.hash` here https://github.com/Project-OSRM/osrm-frontend-v2/blob/redesign/printing.js#L10

**Comment by amyleew** [comment]
Having an issue passing the correct parameters from the `_printPage` function [src/tools.js#L120-L133](https://github.com/Project-OSRM/osrm-frontend-v2/blob/6ceab43409922e01c9c1dbd325a5f99c6d794bbd/src/tools.js#L120-L133) `center`  and `zoom` added to `var options` are legit values

![image](https://cloud.githubusercontent.com/assets/4587826/9611384/5989dc38-50ad-11e5-95f2-d458ec22a603.png)

But the entire `link` values seems to be problematic. In `console.log` you don't see the `options` pass from `links.format(link, options))`

![image](https://cloud.githubusercontent.com/assets/4587826/9611494/f22da7f8-50ad-11e5-87a0-fe2fcd6e634c.png)

It's passed correctly in Patrick's version, and `options` is showing as a proper `object`. 
![image](https://cloud.githubusercontent.com/assets/4587826/9611537/34ddbb74-50ae-11e5-9b12-422c27489231.png)

Which leads me to the functions `formatLink` in [src/links.js#L55-L78](https://github.com/Project-OSRM/osrm-frontend-v2/blob/6ceab43409922e01c9c1dbd325a5f99c6d794bbd/src/links.js#L55-L78) and `parseLink` in [src/links.js#L80-L118](https://github.com/Project-OSRM/osrm-frontend-v2/blob/6ceab43409922e01c9c1dbd325a5f99c6d794bbd/src/links.js#L80-L118). My version seems to jump straight to `parseLink` and not run `formatLink`. 

Is the fix simpler than this @danpat? Feel like I'm getting into deep waters...

**Comment by amyleew** [comment]
Looks like I'm missing some `requires` in [`links.js`](https://github.com/Project-OSRM/osrm-frontend-v2/blob/6ceab43409922e01c9c1dbd325a5f99c6d794bbd/src/links.js#L3-L4) ...

**Comment by amyleew** [comment]
Print working https://github.com/Project-OSRM/osrm-frontend-v2/commit/43bf9ba26724c44f79aa3b6ff19b98b1f5cc4677
