### ISSUE TITLE
[code review] Small TODOs

### ISSUE THREAD

**Issue by tristen** [Project-OSRM/osrm-frontend-v2#97]
I've just had a quick review of the code and I'm seeing a few things worth addressing before the new frontend becomes a thing.
- Replace [this file](https://github.com/Project-OSRM/osrm-frontend-v2/blob/21758f5ee004842eb632d1b69de998b18397f6a0/.jshintrc) with this instead: https://gist.github.com/tristen/3398551b785998ab1033 renaming the file to .eslintrc. You aren't using jshint in this project
- You declare @font-face rules in each of your .css docs. Just do this in one place.
- I would avoid using [base](https://github.com/Project-OSRM/osrm-frontend-
  v2/blob/master/css/base.css). Its a big doc and you aren't using 99% of it. I like to use a reduced version of it on projects not directly related to Mapbox. Here's a gist to one: https://gist.github.com/tristen/414b87abea0dc99df716
- What's the difference between scripts in the [js directory](https://github.com/Project-OSRM/osrm-frontend-v2/tree/master/js) and the [src directory](https://github.com/Project-OSRM/osrm-frontend-v2/tree/master/src)? Consider combining these into one directory (or putting any external libs in a `src/libs` directory) for clarity 
- There are a number of places where you have [commented out code](https://github.com/Project-OSRM/osrm-frontend-v2/blob/21758f5ee004842eb632d1b69de998b18397f6a0/src/tools.js#L134-L169). Remove this stuff for clarity. you can always retrieve old idea's in version control.
- General code formatting is different from line to line. This is picky but makes a huge difference for the long term maintenance of a project. I strongly advise running [`npm test`](https://github.com/Project-OSRM/osrm-frontend-v2/blob/21758f5ee004842eb632d1b69de998b18397f6a0/package.json#L7) a few times and working through standardizing your formatting. It's otherwise hard to read as a newcomer.

**Comment by amyleew** [comment]
Awesome @tristen! Will take a look.

**Comment by amyleew** [comment]
@tristen Fixed and merged all your feedback to `gh-pages` https://github.com/Project-OSRM/osrm-frontend-v2/pull/99. **All but** this one:
- `Error  Move the invocation into the parens that contain the function 4:16` in [src/geocoder.js](https://github.com/Project-OSRM/osrm-frontend-v2/blob/3e1e848859d57e98849ac3666b742cb9ee62e6af/src/geocoder.js) it references the [`wrap-iife`](http://eslint.org/docs/rules/wrap-iife) rule ... Can you take a look  ? 

_Also note:_ Rule `space-after-function-name` was removed and replaced by: [`space-before-function-paren`](http://eslint.org/docs/rules/space-before-function-paren) And I didn't touch the `150 problems` in [`src/libs/leaflet-label.js`](https://github.com/Project-OSRM/osrm-frontend-v2/blob/3e1e848859d57e98849ac3666b742cb9ee62e6af/src/libs/leaflet-label.js).

/cc @lxbarth

**Comment by tristen** [comment]
> Error Move the invocation into the parens that contain the function

This is probably a rule we can ignore. Putting the parens outside of the function is common practice. I would set a flag in the `.eslintrc` file to disable this warning.

> Also note: Rule space-after-function-name was removed and replaced by: space-before-function-paren

Hmm let's avoid this rule all together: a space between the parens and function name.

> And I didn't touch the 150 problems in src/libs/leaflet-label.js.

Might be a good idea to ignore this directory in your `npm test` script. just target `src/*.js` instead.

**Comment by amyleew** [comment]
A few PR's later... Done https://github.com/Project-OSRM/osrm-frontend-v2/pull/107 Had to add `.eslintignore`file for `src/libs/leaflet-label.js`. 

Merged to `gh-pages` http://project-osrm.org/osrm-frontend-v2/

/cc @tristen @lxbarth

**Comment by amyleew** [comment]
@TheMarex - ~~Is there a reason for this repo to have `master` branch? if not, I'll delete it.~~ Thanks

I've deleted it
